baseURL = "https://openmls.tech"
languageCode = "en-us"
title = "OpenMLS"
theme = "hugo-theme-minos"
paginate = 10

[params]
    smartToc = true
    katex = true

[menu]

  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/openmls/openmls"
    weight = -110
